codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 94.0
        threshold: 0.1
      fully_covered:
        target: 100.0
        paths:
          - OpenQA/
          - backend/
          - consoles/
          - commands.pm
          - distribution.pm
          - autotest.pm
          - myjsonrpc.pm
          - lockapi.pm
          - basetest.pm
          - bmwqemu.pm
          - cv.pm
          - log.pm
          - mmapi.pm
          - osutils.pm
          - signalblocker.pm
          - testapi.pm
          - t/
          - xt/
          - script/check_qemu_oom
          - script/vnctest
    patch:
      default:
        branches: null
fixes:
  - "/opt/::"
